"""
Create a program that will play the “cows and bulls” game with the user.
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit
number. For every digit that the user guessed correctly in the correct
place, they have a “cow”. For every digit the user guessed correctly in
the wrong place is a “bull.” Every time the user makes a guess, tell
them how many “cows” and “bulls” they have. Once the user guesses the
correct number, the game is over. Keep track of the number of guesses
the user makes throughout the game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction
could look like this:

    Welcome to the Cows and Bulls Game!
    Enter a number:
    >>> 1234
    2 cows, 0 bulls
    >>> 1256
    1 cow, 1 bull
    ...
Until the user guesses the number.
"""

# Python 2 compatibility imports
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

# Standard Libraries
from random import randint


def main():
    print("Welcome to the Cows and Bulls Game!")
    ans = randint(1000, 9999)
    ans_digits = [x for x in str(ans)]
    # print(ans)
    n_guesses = 0
    cows = 0
    bulls = 0

    while cows != 4:
        user_ans = input("Enter a 4 digit number: ")
        user_ans_digits = [x for x in user_ans]
        n_guesses += 1

        if len(user_ans) < 4:
            print("Error please enter a 4 digit number")
        else:
            for i in range(len(user_ans_digits)):
                if user_ans_digits[i] == ans_digits[i]:
                    cows += 1
                elif user_ans_digits[i] in ans_digits:
                    bulls += 1
            if cows == 4:
                print(
                    "Congrats!! Answer is {} and you guessed {}".format(ans, user_ans)
                )
                print("Number of guesses: {}".format(n_guesses))
            else:
                print("Incorrect guess again")
                print("{} cow(s), {} bull(s)".format(cows, bulls))
                cows = 0
                bulls = 0


if __name__ == "__main__":
    main()
